import * as bank from "./bank/structs";
import * as cpmm from "./cpmm/structs";
import * as events from "./events/structs";
import * as fees from "./fees/structs";
import * as globalAdmin from "./global-admin/structs";
import * as pool from "./pool/structs";
import * as quote from "./quote/structs";
import * as registry from "./registry/structs";
import * as version from "./version/structs";
import {StructClassLoader} from "../_framework/loader";

export function registerClasses(loader: StructClassLoader) { loader.register(version.Version);
loader.register(globalAdmin.GlobalAdmin);
loader.register(registry.BankType);
loader.register(registry.Registry);
loader.register(events.Event);
loader.register(bank.Bank);
loader.register(bank.BurnBTokenEvent);
loader.register(bank.DeployEvent);
loader.register(bank.Lending);
loader.register(bank.MintBTokenEvent);
loader.register(bank.NeedsRebalance);
loader.register(bank.NewBankEvent);
loader.register(bank.RecallEvent);
loader.register(quote.DepositQuote);
loader.register(quote.RedeemQuote);
loader.register(quote.SwapFee);
loader.register(quote.SwapQuote);
loader.register(fees.FeeConfig);
loader.register(fees.Fees);
loader.register(pool.DepositResult);
loader.register(pool.NewPoolResult);
loader.register(pool.Pool);
loader.register(pool.PoolCap);
loader.register(pool.RedeemResult);
loader.register(pool.SwapResult);
loader.register(pool.TradingData);
loader.register(cpmm.CpQuoter);
 }
